markdown: redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", disable_indented_code_blocks, "autolink", "tables", "with_toc_data" ]

title: CM0604
subtitle: Embedded systems specification and design
authors: Michael Brockway, David Kendall
copyyear: 2015-2017
url: http://hesabu.net/cm0604
raurl: http://hesabu.net/cm0604/assets/ra
rraurl: http://cgweb1.northumbria.ac.uk/SubjectAreaResources/CM0605/assets/ra
#url: http://localhost:4000
#raurl: http://localhost:4000/assets/ra

lab_links:
  - title: Lab 01
    url: assets/ra/L01.pdf
    #rep: cm0605_lab01
  - title: Lab 02
    url: assets/ra/L02.pdf
    #rep: cm0605_lab01
  - title: Lab 03
    url: assets/ra/L03.pdf
    #rep: cm0605_lab03
  - title: Lab 04
    url: assets/ra/L04.pdf
    #rep: cm0605_lab01
  - title: Lab 05
    url: assets/ra/L05.pdf
    #rep: cm0605_lab05
  - title: Lab 06
    url: assets/ra/L06.pdf
    #rep: cm0605_lab01
  - title: Lab 07
    url: assets/ra/L07.pdf
    #rep: cm0605_lab07
  - title: Lab 08
    url: assets/ra/L08.pdf
    #rep: cm0605_lab01
  - title: Lab 09
    url: assets/ra/L09.pdf
    #rep: cm0605_lab09
  - title: Lab 10
    url: assets/ra/L10.pdf
    #rep: cm0605_lab01
  - title: Lab 11
    url: assets/ra/L11.pdf
    #rep: cm0605_lab01
  - title: Lab 12
    url: assets/ra/L12.pdf
    #rep: cm0605_lab01
 

right_links:
  - title: View on GitHub
    url: https://github.com/davidkendall/cm0604_www

repo: https://github.com/davidkendall/cm0604

